import { Inter } from 'next/font/google'
import './globals.css'
import Dashboard from './@layout/Dashboard'
import Navbar from './@layout/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <header>
          {/* <Dashboard /> */}
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  )
}
